[project]
    authors      = [{ name = "Lucas Parzianello" }]
    dependencies = ["loguru>=0.7.2", "numpy>=2.1.1", "pandas>=2.2.2"]
    description  = ""
    name         = "kv-store-benchmarks"
    readme       = "README.md"
    version      = "0.1.0"
